apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: hireme
data:
    PORT: "5000"
    DB_STRING: "mongodb://localhost:27017/home_services_platform"
    NODE_ENV: "development"
    API_VERSION: "/v1"
    GMAIL: "raj4122002@gmail.com"
