apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: hireme
type: Opaque
data:
  DB_STRING: mongodb://mongodb-service:27017/home_services_platform
  SECREATE: mySuperSecretKey123
  GMAIL_PASSWORD: rajt9987
