apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: hireme
type: Opaque
data:
  DB_STRING: bW9uZ29kYjovL2xvY2FsaG9zdDoyNzAxNy9ob21lX3NlcnZpY2VzX3BsYXRmb3Jt
  USERNAME: cm9vdA==
  PASSWORD: cm9vdA==


