apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quickhireme-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/r-jkum-r/QuickHireMe.git
    targetRevision: HEAD
    path: k8s/argocd-app
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true