apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  namespace: hireme
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: rajkumarmca23/hireme:latest
          ports:
          - containerPort: 5000
            name: http-server
          envFrom:
          - configMapRef:
              name: app-config
          - secretRef:
              name: app-secret
          # env:
          # - name: NODE_ENV
          #   value: production
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /ready
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10